### ISSUE TITLE
access to the pretrained model

### ISSUE THREAD

**Issue by Sissuire** [junyongyou/phiqnet#1]
Hi, 

Thanks for your sharing of PHIQNET. Will you please share a well-trained model on the two databases for a direct evaluation ?

**Comment by junyongyou** [comment]
Hi, thanks for your interest. The trained model weights can be downloaded here: https://drive.google.com/file/d/1ymy2oL0r-XNzjqk_kE-lcNkI2FhSu95h/view?usp=sharing. I have also update README to include the link.

**Comment by Sissuire** [comment]
@junyongyou Thanks for your sharing.
